version: '3.8'

services:
  # API Gateway
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "8000:8000"
    environment:
      - INPUT_SERVICE_URL=http://input-service:8001
      - TRANSLATION_SERVICE_URL=http://translation-service:8002
      - EVALUATION_SERVICE_URL=http://evaluation-service:8003
      - STORAGE_SERVICE_URL=http://storage-service:8004
    depends_on:
      - input-service
      - translation-service
      - evaluation-service
      - storage-service
    networks:
      - translation-network

  # Input Service
  input-service:
    build: ./services/input-service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=sqlite:///./data/input.db
      - UPLOAD_FOLDER=/app/uploads
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    networks:
      - translation-network

  # Translation Service
  translation-service:
    build: ./services/translation-service
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=sqlite:///./data/translation.db
      - MODEL_PATH=/app/models
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-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}
      - CLAUDE_MODEL=${CLAUDE_MODEL:-claude-3-haiku-20240307}
      - CLAUDE_SYSTEM_PROMPT=${CLAUDE_SYSTEM_PROMPT:-You are a highly skilled Arabic to Urdu translator focused on 100% accuracy with cultural nuances and linguistic precision.}
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    networks:
      - translation-network

  # Evaluation Service
  evaluation-service:
    build: ./services/evaluation-service
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=sqlite:///./data/evaluation.db
      - JWT_SECRET=your-secret-key-here
    volumes:
      - ./data:/app/data
    networks:
      - translation-network

  # Storage Service
  storage-service:
    build: ./services/storage-service
    ports:
      - "8004:8004"
    environment:
      - DATABASE_URL=sqlite:///./data/storage.db
      - EXPORT_FOLDER=/app/exports
    volumes:
      - ./data:/app/data
      - ./exports:/app/exports
    networks:
      - translation-network

  # Frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - api-gateway
    networks:
      - translation-network

networks:
  translation-network:
    driver: bridge

volumes:
  data:
  uploads:
  exports:
  models: 